version: '3'

services:
  gatewayapp:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
    command: /bin/sh -c "/opt/startup.dev.sh"
    env_file:
      - ./apps/gateway/.env
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    depends_on:
      - rabbitmq

  mailingapp:
    build:
      context: .
      dockerfile: ./apps/mailing/Dockerfile
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    command: /bin/sh -c "/opt/startup.dev.sh"
    env_file:
      - ./apps/mailing/.env
    volumes:
      - .:/usr/src/app
    depends_on:
      - rabbitmq
      - maildev
  
  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
  
  maildev:
    build:
      context: .
      dockerfile: Dockerfile.maildev
    env_file:
      - ./apps/mailing/.env
    ports:
      - 1080:1080
      - 1025:1025